# Generated by Django 5.1.7 on 2025-03-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_trainticket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainticket',
            name='user',
        ),
    ]
